### ISSUE TITLE
ANR in SystemObserver.getLocalIPAddress (SystemObserver.java:471)

### ISSUE THREAD

**Issue by mmartinmo** [BranchMetrics/android-branch-deep-linking-attribution#1009]
Hi, we use `io.branch.sdk.android:library:5.2.0` in our Android app and there have been several reported ANR issues originating in your library.

![image](https://user-images.githubusercontent.com/41465214/185147330-9517537e-114f-4536-91c0-377dc086a576.png)

<img width="364" alt="image" src="https://user-images.githubusercontent.com/41465214/184499861-3b98080e-608a-4e97-a49b-6c45f931a923.png">

<img width="364" alt="image" src="https://user-images.githubusercontent.com/41465214/184499871-956ba822-ef7b-4f58-bfe6-220eb2e351b9.png">

Let me know if you need any further info investigating the issue and when can we expect a fix. Thank you!

Edit: Is it allowed to call this init

`Branch.sessionBuilder(this).withCallback(branchReferralInitListener).withData(getIntent() != null ? getIntent().getData() : null).init();
`

from other thread than main thread? That would solve the issue.

**Comment by mmartinmo** [comment]
Hi, do you have any reaction? Or can you at least share if calling init() from non-UI thread is allowed?

**Comment by jf-branch** [comment]
Hi @mmartinmo, I apologize for the delay. Since the Branch SDK interacts with certain Android APIs, that require so,  we would need to be initialized on the main thread. The SDK itself will handle certain tasks on non-UI threads, like our HTTPS POST request automatically.

**Comment by mmartinmo** [comment]
hi @jf-branch , as no one has replied to this for 4 months we are already rolling out an update that is initializing Branch from a non-UI thread. So far it looks good. I will update you on how it influenced the number of ANRs.

**Comment by jf-branch** [comment]
Sweet! Happy to hear it looks good so far! If you are experiencing any ANRs or unexpected issues, please reopen and tag me.
