### ISSUE TITLE
clicked_branch_link is strangely unreliable

### ISSUE THREAD

**Issue by gscpw** [BranchMetrics/android-branch-deep-linking-attribution#1026]
### Describe the bug

I run an app via Android Studio on a USB-C connected Nokia device. I have a deep link saved in `Keep Notes` so I can easily click on it on the device. When I click on the link, I am offered an option to open the link with the app or with Chrome. Choosing either option sometimes provides me either with proper data payload (as expected) or more often than not with `clicked_branch_link = false`.

### Steps to reproduce

This is the behavior I observe if I first choose "open with app":

1. Choose "open with app"
2. I receive `{ "+clicked_branch_link": false, "+is_first_session": false }`
3. Try again, choose "open with app" again
4. I receive again `{ "+clicked_branch_link": false, "+is_first_session": false }`
5. Try for the third time, choose "open with app"
6. I receive `{ "+clicked_branch_link": false, "+is_first_session": false }`
7. Try again, this time choose "open with chrome"
8. I receive `{ "+clicked_branch_link": false, "+is_first_session": false }`
9. Try once more "open with chrome"
10. I receive a proper data payload with all my custom properties, as I wanted
11. Try once more "open with chrome"
12. Again receive proper data payload
13. Try again but now with "open with app"
14. Surprisingly receive proper data payload
15. Try again with "open with app"
16. Receive `{ "+clicked_branch_link": false, "+is_first_session": false }`
17. Try again with "open with chrome"
18. Receive `{ "+clicked_branch_link": false, "+is_first_session": false }`
19. Try again with "open with app"
20. Receive proper data payload

It seems to me the Branch behavior is pretty random, but I observed the following pattern: If I open the link with app, the next time I open a link, it will be `clicked_branch_link = false` no matter what, and it will not have any data payload available. If I open the link with Chrome, it seems to work fine UNLESS the previous link was opened with app, in which case the referringParams will once again have `clicked_branch_link = false`.

### Expected behavior

I would expect the links to work properly no matter if opened with the app or Chrome. Instead, opening the EXACT SAME link with app or Chrome yields varying and almost random results.

### SDK Version

5.2.6

### Make and Model

Nokia 5.3

### OS

11

### Additional Information/Context

It seems this user experienced a similar weird behavior: https://github.com/BranchMetrics/android-branch-deep-linking-attribution/issues/652#issuecomment-453040497

**Comment by jf-branch** [comment]
Hey @gscpw, 

I would suggest to open up a support ticket, often times this can be a testing misunderstanding or an integration issue, but through support you can provide the details needed to identify the issue through logs. 

https://help.branch.io/using-branch/page/submit-a-ticket
