### ISSUE TITLE
Trouble initializing Branch.  Branch API Error: poor network connectivity. Please try again later.

### ISSUE THREAD

**Issue by sunnykraditya** [BranchMetrics/android-branch-deep-linking-attribution#1038]
### Describe the bug

We are getting errors on trying to access a deep link on an android app. 
 

`Trouble initializing Branch.  Branch API Error: poor network connectivity. Please try again later.`
![Screenshot 2023-01-06 at 1 39 05 PM](https://user-images.githubusercontent.com/74891302/210959904-ea44958b-8dcd-4e63-8494-199a5f684bbd.png)

Any workarounds for this?

### Steps to reproduce

1. Click on a Deep link 
2. Observe deep link fails to resolve

### Expected behavior

Branch session should initialise and resolve the deep link

### SDK Version

5.2.6 

### Make and Model

Pixel 4a emulator, Samsung device

### OS

11

**Comment by Binusz** [comment]
I have the same issue on Android 13 (API 33). It is an interesting issue because it works when I switch to API 32.

**Comment by zgfliusha** [comment]
I have encountered the same problem. Have you resolved it?

**Comment by thisisritesh** [comment]
I am facing a similar issue. It says ` {"error_message":"Trouble reaching server. Please try again in a few minutes"}` Please let me know if anyone has resolved it.

**Comment by ritesh-shop2app** [comment]
I am facing a similar issue says  `{"error_message":"Trouble reaching server. Please try again in a few minutes"}`

**Comment by ritesh-shop2app** [comment]
Facing a similar issue says `{"error_message":"Trouble reaching server. Please try again in a few minutes"}`

**Comment by gdeluna-branch** [comment]
This particular error can be the result of DNS policies. More descriptive error handling is in the latest https://github.com/BranchMetrics/android-branch-deep-linking-attribution/releases/tag/5.7.3

**Comment by rushant11** [comment]
> I have the same issue on Android 13 (API 33). It is an interesting issue because it works when I switch to API 32.

Did you get the solution of this error?

**Comment by rushant11** [comment]
> I have encountered the same problem. Have you resolved it?

Did you get the solution of this error?

**Comment by rushant11** [comment]
> Facing a similar issue says `{"error_message":"Trouble reaching server. Please try again in a few minutes"}`

Did you get the solution of this error?

**Comment by rushant11** [comment]
> ### Describe the bug
> We are getting errors on trying to access a deep link on an android app.
> 
> `Trouble initializing Branch. Branch API Error: poor network connectivity. Please try again later.` ![Screenshot 2023-01-06 at 1 39 05 PM](https://user-images.githubusercontent.com/74891302/210959904-ea44958b-8dcd-4e63-8494-199a5f684bbd.png)
> 
> Any workarounds for this?
> 
> ### Steps to reproduce
> 1. Click on a Deep link
> 2. Observe deep link fails to resolve
> 
> ### Expected behavior
> Branch session should initialise and resolve the deep link
> 
> ### SDK Version
> 5.2.6
> 
> ### Make and Model
> Pixel 4a emulator, Samsung device
> 
> ### OS
> 11
> 
> ### Additional Information/Context
> _No response_

Plz give me the solution of this error?

**Comment by umeshcodealchemy** [comment]
Please check your internet connection and try using a stronger network connection.
