### ISSUE TITLE
To target the latest Android version, please update your PBL version to either 5.2.1, or 6.0.1 and above

### ISSUE THREAD

**Issue by kk-atom** [BranchMetrics/android-branch-deep-linking-attribution#1088]
### Describe the bug

![image](https://github.com/BranchMetrics/android-branch-deep-linking-attribution/assets/112948793/a71d0055-58a3-44fc-9f2f-7ee8468d7c6c)

Why billing library is included?
```
+--- io.branch.sdk.android:library:5.6.1
|    +--- org.jetbrains.kotlin:kotlin-stdlib:1.6.20 -> 1.8.21 (*)
|    +--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.6.20 -> 1.8.21 (*)
|    +--- androidx.annotation:annotation:1.4.0 -> 1.6.0 (*)
|    +--- com.android.installreferrer:installreferrer:2.2
|    +--- com.google.firebase:firebase-appindexing:19.0.0
|    |    +--- androidx.collection:collection:1.0.0 -> 1.2.0 (*)
|    |    +--- androidx.core:core:1.0.0 -> 1.11.0-beta02 (*)
|    |    +--- com.google.android.gms:play-services-base:17.0.0 -> 18.2.0 (*)
|    |    +--- com.google.android.gms:play-services-basement:17.0.0 -> 18.2.0 (*)
|    |    +--- com.google.android.gms:play-services-tasks:17.0.0 -> 18.0.2 (*)
|    |    \--- com.google.firebase:firebase-common:18.0.0 -> 20.3.3 (*)
|    +--- com.android.billingclient:billing:5.1.0
|    \--- androidx.test.ext:junit-ktx:1.1.5
```

### Steps to reproduce

1.
2.
3.

### Expected behavior

Remove billing library.

### SDK Version

5.6.1

### Make and Model

any

### OS

any

**Comment by gdeluna-branch** [comment]
We'll have a patch to make this optional. cc @nsingh-branch @jf-branch

**Comment by TimothyChilvers** [comment]
Just echoing, this is causing us some problems as the specific JUnit version is downgrading some of our other dependencies that they are no longer compatible.

**Comment by gdeluna-branch** [comment]
We should be releasing this patch today.

**Comment by gdeluna-branch** [comment]
Now optional as of 5.6.2

https://central.sonatype.com/artifact/io.branch.sdk.android/library/5.6.2
https://github.com/BranchMetrics/android-branch-deep-linking-attribution/releases/tag/5.6.2

Please reopen if you still have issue with this. Or open a new issue for other errors.
Thanks
