### ISSUE TITLE
R8: Missing class

### ISSUE THREAD

**Issue by kk-atom** [BranchMetrics/android-branch-deep-linking-attribution#1111]
### Describe the bug

ERROR: R8: Missing class com.google.android.gms.ads.identifier.AdvertisingIdClient$Info (referenced from: java.lang.Object io.branch.coroutines.AdvertisingIdsKt$getGoogleAdvertisingInfoObject$2.invokeSuspend(java.lang.Object) and 1 other context)
Missing class com.google.android.gms.ads.identifier.AdvertisingIdClient (referenced from: java.lang.Object io.branch.coroutines.AdvertisingIdsKt$getGoogleAdvertisingInfoObject$2.invokeSuspend(java.lang.Object))

### Steps to reproduce

1.
2.
3.

### Expected behavior

-

### SDK Version

5.6.4

### Make and Model

-

### OS

-

**Comment by gdeluna-branch** [comment]
fixed as of 5.7.0
