### ISSUE TITLE
Catch IllegalStateException in executeTask

### ISSUE THREAD

**Issue by cocoslime** [BranchMetrics/android-branch-deep-linking-attribution#1126]
### Describe the bug

11:31:37.857  W  java.lang.IllegalStateException: Cannot execute task: the task is already running.
11:31:37.858  W  	at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:713)
11:31:37.858  W  	at android.os.AsyncTask.execute(AsyncTask.java:671)
11:31:37.858  W  	at io.branch.referral.BranchAsyncTask.executeTask(BranchAsyncTask.java:23)
11:31:37.858  W  	at io.branch.referral.Branch.executeTimedBranchPostTask(Branch.java:1756)
11:31:37.858  W  	at io.branch.referral.Branch.processNextQueueItem(Branch.java:1736)
11:31:37.858  W  	at io.branch.referral.Branch.onIntentReady(Branch.java:2093)
11:31:37.858  W  	at io.branch.referral.BranchActivityLifecycleObserver.onActivityResumed(BranchActivityLifecycleObserver.java:65)
11:31:37.858  W  	at android.app.Application.dispatchActivityResumed(Application.java:450)
11:31:37.858  W  	at android.app.Activity.dispatchActivityResumed(Activity.java:1483)
11:31:37.858  W  	at android.app.Activity.onResume(Activity.java:2055)
11:31:37.858  W  	at androidx.fragment.app.FragmentActivity.onResume(FragmentActivity.java:309)

### Steps to reproduce

executeOnExecutor(AsyncTask.THREAD_POOL_EXECUTOR, params) (BranchAsyncTask.java:21)
     at executeTimedBranchPostTask (Branch.java:1752)

1. When it throws Exception from unknown reason after RUNNING, it will be caught in BranchAsyncTask.java:23
2. Because task is already running, it will throw IllegalStateException.
3. There is no way to catch this exception and task doesn't remove from queue.

### Expected behavior

The task should be removed from queue, when it makes unknown exception.

### SDK Version

5.6.1

### Make and Model

Samsung S23

### OS

13

**Comment by gdeluna-branch** [comment]
We expect to have the deprecated AsyncTasks removed in the near future, but if you happen to have a repro I can look further into it.

**Comment by cocoslime** [comment]
Our Issue is solved from 5.7.1 `Fixed bug that prevented session from initializing after opening a link with gclid`.
I'll close this issue. Thank you!
