### ISSUE TITLE
Broken BranchLogger in V5.8.0

### ISSUE THREAD

**Issue by prateekkejriwal** [BranchMetrics/android-branch-deep-linking-attribution#1158]
### Describe the bug

With the release of V5.8.0, Branch SDK is unable to log the messages on the Android Logger. 

There is an addition of another value ( isDebug ) in the [BranchLogger.kt ](https://github.com/BranchMetrics/android-branch-deep-linking-attribution/blob/6a3111b0c8e58e74fa73e893eac1a06945d3152f/Branch-SDK/src/main/java/io/branch/referral/BranchLogger.kt#L16) here.

This value is set using BuildConfig.DEBUG which is referencing to the BuildConfig.DEBUG of the SDK and not the actual application. Because of this check, SDK is unable to print any logs even with logging enabled.

Test Details - 

SDK Version - 5.8.0 
Android Version - 14
Device - Samsung S22 Ultra
Test App Attached. 
[My Application.zip](https://github.com/BranchMetrics/android-branch-deep-linking-attribution/files/13819536/My.Application.zip)

[My Application_5dot7dot5.zip](https://github.com/BranchMetrics/android-branch-deep-linking-attribution/files/13819571/My.Application_5dot7dot5.zip). Same app with SDK version 5.7.5 with working logs. 

### Steps to reproduce

1.Integrate Branch SDK as per the help docs [here](https://help.branch.io/developers-hub/docs/android-basic-integration). 
2.Run the app through debugger on  a physical or an emulator device.
3. Check the Logcat for logs printed by Branch SDK.

OR 

Use the provided app source.
1. Import the project into Android Studio
2. Run the app through debugger on  a physical or an emulator device.
3. Check the Logcat for logs printed by Branch SDK.

### Expected behavior

Branch SDK should have printed logs on the log cat.

### SDK Version

5.8.0

### Make and Model

S22 Ultra

### OS

14

**Comment by gdeluna-branch** [comment]
Fixed in 5.8.1
