### ISSUE TITLE
Google Ads conversions not working correctly

### ISSUE THREAD

**Issue by desmeit** [BranchMetrics/android-branch-deep-linking-attribution#1166]
### Describe the bug

We have a problem with Google Ads. It seems to be installed correctly, even if it took a long time until it was shown in analytics, but the installations are not correct.
I see only 2 installs although Google Ads shows more than 160. I have done all the steps correctly:

- Added linked Apps to Google Ads
- Added Partner Google Ads to branch with the App IDs
- Import Conversions first_open to Google Ads

I have two projects with the same issue.

There are two problems:

1. first_open is ONLY displayed for IOS in Google Ads under Conversions. Android does not appear. I have recreated the link several times, waited, tried to import again. It does not work. Why does first_open not appear in Google Ads for Android?

2. for our other app the first_open is also correctly imported as a conversion for Android in Google. But it still took days before anything was displayed in Branch. The clicks and costs seem to be correct, but the installations are definitely wrong. 2 instead of 160 are displayed. There seems to be a bug in the SDK. In Google Ads, it also only shows 2 for the branch conversion first_open. It seems it is reporting not correctly from the SDK.

By the way: Tik Tok is not reported at all. The Tik Tok support answered me as follows:

`Postback logs from the MMP with the 'value' parameters passed to TikTok for the campaign IDs reported with the issue.`

Overall, the integration of the advertising partners at Branch does not seem to work properly and the support does not seem to work either.

What can I do? Support is not answering. It seems there is an issue in the SDK which is reporting wrong installs to Google Ads.

https://github.com/RodrigoSMarques/flutter_branch_sdk/issues/292#issuecomment-1925307279

### Steps to reproduce

1. first_open is ONLY displayed for IOS in Google Ads under Conversions. Android does not appear. I have recreated the link several times, waited, tried to import again. It does not work. Why does first_open not appear in Google Ads for Android?

2. for our other app the first_open is also correctly imported as a conversion for Android in Google. But it still took days before anything was displayed in Branch. The clicks and costs seem to be correct, but the installations are definitely wrong. 2 instead of 160 are displayed. There seems to be a bug in the SDK. In Google Ads, it also only shows 2 for the branch conversion first_open. It seems it is reporting not correctly from the SDK.

### Expected behavior

Seeing Installs from Google Ads in Branch

### SDK Version

flutter_branch_sdk 7.0.4

### Make and Model

xxx

### OS

xxx

**Comment by RodrigoSMarques** [comment]
@desmeit 

The flutter plugin uses the SDK versions below.
iOS - 3.0.1
Android - 5.8.2

It's not a problem with the Flutter plugin, as it is just a bridge between the native SDK and Flutter.

I will be closing your issue on Flutter.
