### ISSUE TITLE
New method Branch.getInstance().share() not calling callback funcitions

### ISSUE THREAD

**Issue by RodrigoSMarques** [BranchMetrics/android-branch-deep-linking-attribution#1175]
### Describe the bug

The new method `Branch.getInstance().share()`  is not calling the callback function `Branch.BranchNativeLinkShareListener` (`onLinkShareResponse` and `onChannelSelected`)

The `showShareSheet` method (which was deprecated) it worked correctly.

### Steps to reproduce

1. Implement the code for the `Branch.getInstance().share()` function and include the `Branch.BranchNativeLinkShareListener` callback functions
2. call `Branch.getInstance().share()`
3. Callback functions not call

### Expected behavior

Call `Branch.BranchNativeLinkShareListener` functions after sharing.

### SDK Version

5.10.0 / 5.10.1

### Make and Model

Samsung S20 SE / Samsung J5 Prime / Nexus 5 (Emulator)

### OS

13 / 8.1 / 14

**Comment by RodrigoSMarques** [comment]
Analyzing PR #1156 , I identified that it is necessary to include `SharingBroadcastReceiver` in `AndroidManifest.xml`.


```xml
<receiver android:name="io.branch.receivers.SharingBroadcastReceiver" android:exported="true">
           <intent-filter>
               <action android:name="EXTRA_CHOSEN_COMPONENT" />
           </intent-filter>
       </receiver>
```
These instructions are not in the documentation.

**Comment by gdeluna-branch** [comment]
@NidhiDixit09 Can you add this step to our docs?

**Comment by RodrigoSMarques** [comment]
documentation has been updated
