### ISSUE TITLE
non_branch_link sometimes is transformed to '/open' path

### ISSUE THREAD

**Issue by vasa137** [BranchMetrics/android-branch-deep-linking-attribution#1188]
### Describe the bug

When I try to open the app with the non-branch deep link, non_branch_link field sometimes doesn't provide the url I've clicked on.

### Steps to reproduce

1.Steps to reproduce the behavior:

1. I've clicked on the link with the custom domain: dev-app.operi.rs/home/orders
2. Branch SDK returned this: "+non_branch_link":"dev-operi-app://open?link_click_id=1304070486333205728"

### Expected behavior

I've expected to get non_branch_link = dev-app.operi.rs/home/orders

### SDK Version

5.11.+

### Make and Model

Samsung Galaxy S21 FE

### OS

14

### Additional Information/Context

In some periods of the day - the expect behavior is happening, but mostly it returns dev-operi-app://open?link_click_id=XXX. Also, on Xiaomi I've never received this type of the response - it's always the original link.

**Comment by echo-branch** [comment]
@vasa137 
Could you open a support ticket for this one? Our response times are usually much faster there.
https://help.branch.io/using-branch/page/submit-a-ticket

**Comment by vasa137** [comment]
Ticket opened - 00381644

**Comment by vasa137** [comment]
I think the only option is to Generate the link on the Branch portal - since nonBranch links which are using the same domain you registered on Branch Portal will return this thing....

I reached support - but no luck.

**Comment by 0aps** [comment]
this is still a problem
