### ISSUE TITLE
Manual opening deeplink

### ISSUE THREAD

**Issue by petersamokhin** [BranchMetrics/android-branch-deep-linking-attribution#686]
Hello!

My question is about the parsing of params:
for example, I have an onboarding in the app, the page of it's containing a deep link.
If I will use default handler, the SplashActivity will be opened (i.e. app is restarted by Intent).
And this logic is like:
> In-app onboarding page 
→ deep link → click 
→ system is sending Intent(ACTION_VIEW)
→ SplashActitivity is started (app is restarted) 
→ BranchSDK is parsing URI from `intent.data` 
→ BranchReferralInitListener is called 
→ I can handle JSON referring params (simply route to necessary page)

And logic that is needed:
> In-app onboarding page
→ deep link → click 
→ (some BranchSDK method is called, but app not restarted)
→ BranchReferralInitListener is called 
→ I can handle JSON referring params (simply route to necessary page)

So in two words: route to the necessary page from a deep link from the app without restarting of an app.
( yes I don't want to manually parse the URI :D, if your SDK is already used in project )

**Comment by echo-branch** [comment]
This should be supported in recent releases.  It was not supported at the time of the ticket though.
