### ISSUE TITLE
Branch Link Doesn't Work via SMS on Pixel 3 Messages App or TextNow

### ISSUE THREAD

**Issue by projectAZB** [BranchMetrics/android-branch-deep-linking-attribution#693]
In our app, the backend creates the Branch link and sends it out via SMS, but when the Android app receives it through the native Message App or a 3rd-Party SMS app like TextNow the link either doesn't open (as is the case with Messages) or with TextNow it opens up in the custom WebView. This was tested with both a Pixel 1, Pixel 2, and Pixel 3. 
However, in both these cases, if the link is copied and pasted into a Google Mail message and sent then clicked it opens up as expected.

**Comment by csalmi-branch** [comment]
@projectAZB what version of Android and the branch SDK are you using?

**Comment by csalmi-branch** [comment]
@projectAZB are you still experiencing this issue?

**Comment by csalmi-branch** [comment]
Due to the age and inactivity of this issue, I am closing this now. If you are encountering this problem still, please reach out to our support team (support.branch.io) or open a new github issue and we would be happy to help you out!
