### ISSUE TITLE
AndroidX

### ISSUE THREAD

**Issue by eygraber** [BranchMetrics/android-branch-deep-linking-attribution#697]
Please update to use androidx dependencies. This library is the only thing preventing us from turning off jetifier.

**Comment by uziassantosferreira** [comment]
is there any solution to this?

**Comment by apeterson-branch** [comment]
https://github.com/BranchMetrics/android-branch-deep-linking-attribution/pull/713

**Comment by csalmi-branch** [comment]
We have updated dependancies to use AndroidX as part of v4.0.0.
