### ISSUE TITLE
deep link first redirect browser then navigate in app in android

### ISSUE THREAD

**Issue by bonjourrohit89** [BranchMetrics/android-branch-deep-linking-attribution#707]
Hi Team,
I am facing a problem in deeplinking. when I am sharing a link via deep linking. Now when I click that link first it redirect to browser then after it will redirect in app or if app is not installed then it redirect to play store.
But if I test same in IOS then it will directly navigate to app. it's not redirecting in browser.

I want to know why it's first redirect to browser and then navigate in app in android.

Thanks in Advance.

**Comment by csalmi-branch** [comment]
Hi @bonjourrohit89. Are you still experiencing this issue? If so, could you provide an example of your link?

**Comment by Anuj-Kumar-Sharma** [comment]
Facing the same issue. Is there a setting in the branch dashboard or some config to be set up in Android.

**Comment by echo-branch** [comment]
@Anuj-Kumar-Sharma 
Please file a ticket with our support team.  They will be able to spend more time figuring out if it's a config issue or a bug.  Thank you.
