### ISSUE TITLE
"clicked_branch_link" always false, "https" link delivered as "non_branch_link"

### ISSUE THREAD

**Issue by SonjaMijatovic** [BranchMetrics/android-branch-deep-linking-attribution#714]
Hi there,
I'm implementing deeplinking using Branch documentation. 
Here is what I did

Android Manifest:
```

       <activity
            android:name="SplashScreenActivity"
            android:launchMode="singleTask">

            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
                <action android:name="android.intent.action.VIEW" />
            </intent-filter>

            <intent-filter android:label="@string/appName">
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="@string/deep_link_scheme" />
            </intent-filter>

            <intent-filter android:autoVerify="true">
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data
                    android:host="@string/universal_link_host"
                    android:scheme="@string/universal_link_scheme" />
            </intent-filter>

        </activity>
```

where universal_link_host is 'https' and universal_link_scheme is 'myscheme.app.link'

Application class:
```
private fun setupBranch() {
        if (BuildConfig.BUILD_TYPE == "debug") {
            Branch.enableTestMode()
            Branch.enableDebugMode()
        }
        Branch.getAutoInstance(this)
    }
```

Splash screen:

```
override fun onStart() {
        super.onStart()
        Branch.getInstance()
                .initSession({ referringParams, error ->
                                 if (error == null) {
                                     Timber.e("deep params: $referringParams")
                                     val uri = intent.data
                                     if (uri != null) {
                                         deepLinkToOpen = uri.toString()
                                                 .substringAfter("://")
                                     }
                                         val intent = Intent(this, MainActivity::class.java)
                                         intent.putExtra(MainActivity.DEEPLINK, deepLinkToOpen)
                                         startActivity(intent)
                                 } else {
                                     Timber.e("Branch deep link error: ${error.message}")
                                 }
                             }, this.intent.data, this)
    }
```

Custom scheme links are delivered like this:
`{"+non_branch_link":"deep_link_scheme://link","+clicked_branch_link":false,"+is_first_session":false}` and I think that is as expected.

The issue is that https links are also delivered as non_branch_link and clicked_branch_link is always false:
`deep params {"+non_branch_link":"https://myscheme.app.link/dev/link","+clicked_branch_link":false,"+is_first_session":false}`

Am I missing something obvious here?
Thank you!

**Comment by Abdelsattar** [comment]
adding this to your manifest 

`  
        <meta-data android:name="io.branch.sdk.BranchKey" android:value="@string/branch_io_live_key" />
        <meta-data android:name="io.branch.sdk.BranchKey.test" android:value="@string/branch_io_test_key" />

        
        <meta-data android:name="io.branch.sdk.TestMode" android:value="true" />

        
        <receiver android:name="io.branch.referral.InstallListener" android:exported="true">
            <intent-filter>
                <action android:name="com.android.vending.INSTALL_REFERRER" />
            </intent-filter>
        </receiver>
`

**Comment by squeeish** [comment]
I'm getting this as well for practically all custom links that used to work for my app.

```
"data":"{\"+non_branch_link\":\"https://open?link_click_id=685393634411320941\",\"+clicked_branch_link\":false,\"+is_first_session\":false}","device_fingerprint_id":"695304432393135995"}
```

This didn't use to happen. Is this due to a temporary Branch issue?

**Comment by nitzanw** [comment]
I'm getting the same issue.
what seems to be the issue?

**Comment by franzwarning** [comment]
Also getting the issue. Whats up?

**Comment by JSBmanD** [comment]
I'm also with this issue. Any updates?

**Comment by pauloftneto** [comment]
Start facing the same problem, does anyone have a solution?

**Comment by MihaelIsaev** [comment]
Also getting `non_branch_link`, any solution?

**Comment by echo-branch** [comment]
Please file a support ticket for this type of issue.  There's a few different potential causes for this and support can spend more time helping to resolve it.  In particular, a few server side issues can cause this.

Closing.
