### ISSUE TITLE
Branch.getInstance().logout() dosn't work or dosn't clear history!

### ISSUE THREAD

**Issue by mwaked** [BranchMetrics/android-branch-deep-linking-attribution#715]
Hi there,

Please i have a problem with branch, i can't make logout, and branch keep return  referringParams every time i open the app and init session.

// I used this code for initSession and logout

 override fun onStart() {
        super.onStart()
        initBranch()
    }

    private fun initBranch() {
        Branch.getInstance().initSession({ referringParams, error ->
            if (error == null) {
                Log.d(TAG, referringParams.toString())
                    Handler().postDelayed({
                        startActivity<ProfileActivity>(ProfileActivity.newIntent(presenterId))
                        Branch.getInstance().logout()
                    }, 500)
              
            } else Log.d(TAG, error.message)
        }, this.intent.data, this)
    }

Am I missing something obvious here?
Thank you

**Comment by apeterson-branch** [comment]
Investigating...

**Comment by csalmi-branch** [comment]
@mwaked301 We weren't able to reproduce this yet. Are you still experiencing the issue? Is so, could you provide us with more details around your configuration, and what version of the SDK you are using?

**Comment by echo-branch** [comment]
Closing due to no response from reporter.
