### ISSUE TITLE
Branch links are not clickable in Xiaomi mi devices

### ISSUE THREAD

**Issue by deepti1408** [BranchMetrics/android-branch-deep-linking-attribution#717]
wrt closed issue: #609 branch.io link is not working on MI devices when link shared by SMS.

This issues still persists. Please provide a solution for the same.

**Comment by deepti1408** [comment]
#609

**Comment by csalmi-branch** [comment]
@deepti1408 Can you provide more details? What SDK version are you using? Which version of android is on the device? Is it only the Xiaomi mi devices, or are you able to reproduce it on other devices?

**Comment by derrick-branch** [comment]
Please write in to support@branch.io if this issue persists, providing an answer to the below.
