### ISSUE TITLE
add branch key pragmatically

### ISSUE THREAD

**Issue by SetareMaghari** [BranchMetrics/android-branch-deep-linking-attribution#718]
hey
i have a question about adding branch key in project
i need to add the key through code 
is there a way to add this key without using manifest file in android?

**Comment by apeterson-branch** [comment]
Yes, you can initialize with a key.   Please take a look at
* https://github.com/BranchMetrics/android-branch-deep-linking-attribution/blob/4e36ede86fc329d9b6c94918f0b8d58eb76fc344/Branch-SDK/src/io/branch/referral/Branch.java#L736

I would recommend calling this from your `Application` class, to ensure that Branch is configured before your first activity comes up.

**Comment by csalmi-branch** [comment]
@SetareMaghari did the answer above help solve your issue?

**Comment by echo-branch** [comment]
Closing due to no response from reporter.
