### ISSUE TITLE
directly open whatsapp and not open share style sheet

### ISSUE THREAD

**Issue by surbhiv25** [BranchMetrics/android-branch-deep-linking-attribution#720]
I am not getting any functionality to directly open WhatsApp from my app when I want to share something.

Using your docs, it showed that share style sheet will be opened with the default "copy link" option.Is there anything using which I can directly redirect to whatsapp?

**Comment by csalmi-branch** [comment]
Thanks for reaching out @surbhiv25! We can create links to WhatsApp, but we cannot provide functionality to deeplink directly into an app that isn't your own.

**Comment by derrick-branch** [comment]
@surbhiv25 linking *to* WhatsApp is beyond the scope of what Branch provides. You could research URIs / Intents to open WhatsApp. https://faq.whatsapp.com/en/android/28000012 might be a starting point.
