### ISSUE TITLE
App already Installed and clicking on deeplink, it not opening app

### ISSUE THREAD

**Issue by ManzzBaria** [BranchMetrics/android-branch-deep-linking-attribution#722]
If there is a bug or error in this repo, please file the issue here. 

If you need assistance integrating a Branch SDK, please email support@branch.io. Thank you.

The app already Installed and clicking on deep link, it not opening the app, instead of its redirecting user to the link URL. 

If app already installed and click on deeplink i want to open installed app.

Can anyone help me here?

**Comment by code-crusher** [comment]
@ManzzBaria;

This looks like Android App links setup issue. Can you follow our troubleshooting guide here: https://support.branch.io/support/solutions/articles/6000190963-android-app-not-opening-via-app-links?

**Comment by csalmi-branch** [comment]
@ManzzBaria did the answer above help solve your issue? If not, can you provide some more details about your configuration?

**Comment by echo-branch** [comment]
closing due to no response from reporter
