### ISSUE TITLE
Branch is not routing to the calling fragment

### ISSUE THREAD

**Issue by Wajahat-Jawaid** [BranchMetrics/android-branch-deep-linking-attribution#732]
My app architecture is based on fragments on top of a single activity in the whole app. I'm creating different **BranchUniversalObject** in different fragments. But on every link it takes me to the MainActivity.
Please help me if my intended functionality could be done!

**Comment by apeterson-branch** [comment]
Would something like this help:
```
    @Test
    public void testBuoRouting() {
        BranchUniversalObject buo = new BranchUniversalObject();
        ContentMetadata metadata = new ContentMetadata();

        // Identify which fragment was used to create the BUO
        metadata.setProductVariant("Variant1");

        buo.setContentMetadata(metadata);

        JSONObject jsonObject = buo.convertToJson();
        Log.d("Branch::testBuoRouting", jsonObject.toString());
    }
```

Produces something that looks like this:
```
{
    "$product_variant": "Variant1",
    "$publicly_indexable": true,
    "$locally_indexable": true,
    "$creation_timestamp": 1571071280576
}
```

Your activity could then decide which fragment would be best to handle the response.

**Comment by echo-branch** [comment]
Closing due to no response from reporter.
