### ISSUE TITLE
BranchUniversalReferralInitListener not called when "doesn't pass regex" error

### ISSUE THREAD

**Issue by Danyaga** [BranchMetrics/android-branch-deep-linking-attribution#758]
I have the app stuck at the splash screen, after the opening with some "Quick Links", because, as i told [here (still waiting for an answer BTW)](https://github.com/BranchMetrics/android-branch-deep-linking-attribution/issues/753), I had to wait for your call of the given BranchUniversalReferralInitListener object at Branch.getAutoInstance(context.applicationContext).initSession() and you never call it when this error happens:

```
BranchSDK: returned {"error":{"instrumentation":[],"link_identifier":"doesn't pass regex","metadata":[],"advertising_ids":[]}}
Branch API Error: Conflicting resource error code from API
```

EDIT
The links are posted on Facebook, in case it can help you in the debug.

**Comment by bklastaitis-branch** [comment]
@Danyaga this was a transient issue and only links created between 25th to 28th Oct and scraped by FB were affected. This bug should not be present anymore, but if you are still facing the issue please make sure the link you are testing with is added in the input box here: https://developers.facebook.com/tools/debug/sharing/ and then the **Scrape Button** button is pressed.

**Comment by echo-branch** [comment]
Believe this issue was resolved.
