### ISSUE TITLE
LifecyclerObserver causing performance problems

### ISSUE THREAD

**Issue by amankgo** [BranchMetrics/android-branch-deep-linking-attribution#764]
We were profiling our app performance and noticed that the Branch Application lifecycle callbacks were impacting our screens. We tested for validating this impact and removed a few libraries that register lifecycle callbacks. We are able to see 15% - 18% dip in frozen frames on every screen as these were doing some heavy operations on the main thread (This is a consolidated number in which branch also contributes). 

We would like you to analyze this and recommend possible solutions.

Class: BranchActivityLifeCycleObserver
Possible Method Impacting: startSession(Activity activity)

Even creating a dummy activity, onResume/onStart will impact on our app performance metrics.

Attaching a screenshot for the same. 
Environment: Debug build using Profiler in Android Studio on Samsung A30. On a lower-end device, this number might be much bigger.

<img width="359" alt="Screenshot 2019-10-23 at 7 05 13 PM" src="https://user-images.githubusercontent.com/40785614/68366484-71221e80-0159-11ea-8a2e-4f30e2dd9935.png">
<img width="1161" alt="Screenshot 2019-11-07 at 12 16 44 PM" src="https://user-images.githubusercontent.com/40785614/68366485-71bab500-0159-11ea-9936-d104e70d6141.png">

**Comment by bharath31** [comment]
@amankgo The upcoming release will remove `startSession` from the lifecycle observer, so performance should improve.

**Comment by amankgo** [comment]
Just a quick question: Why do you need to call initSession() in every Activity's onResume (BranchActivityLifecycleObserver)? I can understand for the launcher activities it is ok, but for all other activities, it doesn't seem necessary. Can't we have some kind of additional control which we can use to turn on and off this initSession() call in onResume.
