### ISSUE TITLE
Install receiver deprecated by google

### ISSUE THREAD

**Issue by motorro** [BranchMetrics/android-branch-deep-linking-attribution#778]
I've received a letter from Google where they announce INSTALL_REFERRER deprecation with a migration to [install referrer library](https://developer.android.com/google/play/installreferrer/library.html):

> We recently announced that we’ll be deprecating the install_referrer intent broadcast mechanism. Because one or more of your apps uses this intent to track referrals, we wanted to ensure you make the switch before March 1, 2020. After this date, new versions of the Play Store app will no longer broadcast the install_referrer intent after app installs.

Will there be any updates on Branch SDK to address that?
It would be great if you could also provide a way to notify Branch manually in case I have a custom receiver of new google style like I do it now by calling this in custom receiver:
```kotlin
io.branch.referral.InstallListener().onReceive(context, intent)
```
Thanks!

**Comment by ubuntudroid** [comment]
Well, the new API allows branch and other tracking providers to handle this fully transparently without any need of involvement for app developers. In the best case the migration for app developers would just contain one step: remove the install receiver from your manifest and done.

Our apps will run into serious trouble if this isn't changed well before March 1 as all the apps need to be updated and rolled out - all install attribution will simply stop working. Would be great to get some quick feedback here from the branch devs.

**Comment by AntRemo** [comment]
Same. 

Would feel **much** more comfortable with guidance on how to proceed. 

Thanks 🙏

**Comment by JimmyDeemo** [comment]
Linking the Unity issue.

https://github.com/BranchMetrics/unity-branch-deep-linking-attribution/issues/171

Clarification that nothing needs to be done except what has been indicated would be great.

**Comment by easyonebd** [comment]
Hi @ubuntudroid 
I tried to add Branch SDK to one of my client apps, but the android studio report that InstallListener does not exist in the specified package io.branch.referral.InstallListener but your doc says to add like this
<receiver android:name="io.branch.referral.InstallListener" android:exported="true">
            <intent-filter>
                <action android:name="com.android.vending.INSTALL_REFERRER" />
            </intent-filter>
        </receiver>
while that file doesn't exist will it work if I remove the above lines or I should keep?
please let me know.
thanks in Advanced.

**Comment by ubuntudroid** [comment]
@easyonebd I am not a maintainer of this repository. ;)

**Comment by motorro** [comment]
@easyonebd 
Here is a pull request where they have dropped install listener: #791 
That is version 4.3.1
And here is a ticket from @Danyaga with the same problem and a solution from Branch email support: #804

**Comment by echo-branch** [comment]
This should be fixed in the latest release.
