### ISSUE TITLE
BRANCH SDK FailTrouble initializing Branch

### ISSUE THREAD

**Issue by AmitPrajapati1902** [BranchMetrics/android-branch-deep-linking-attribution#779]
I'm using branch io version 4.2.0

Sometime i'm able to generate that share link, but sometime its not work properly. Branch IO SDK behaviours is weird.

> 
> BranchSDK: !SDK-VERSION-STRING!:io.branch.sdk.android:library:4.2.0
> 
> I/BranchSDK: Http connect exception: SSL handshake aborted: ssl=0x7bcb89b888: I/O error during system call, Connection reset by peer
> 
> BRANCH SDK FailTrouble initializing Branch. Branch API Error: poor network connectivity. Please try again later.
> 
> I/BranchSDK: Branch Error: User session has not been initialized!

    override fun onStart() {
        super.onStart()
        // Branch init
        val branch = Branch.getInstance(applicationContext)
        branch.setRetryCount(5)
        branch.initSession({ referringParams, error ->
            if (error == null) {
                LogUtils.d("BRANCH SDK Success $referringParams")
                if (referringParams.has(Constants.KEY_REFERRAL_CODE) && referringParams.getString(Constants.KEY_REFERRAL_CODE) != null && referringParams.getString(Constants.KEY_REFERRAL_CODE).isNotEmpty()) {
                    val code = referringParams.getString(Constants.KEY_REFERRAL_CODE)
                    LogUtils.d("BRANCH SDK Success Code $code")

                    OnusUtils.setReferralCode(code)
                }
                // Retrieve deep link keys from 'referringParams' and evaluate the values to determine where to route the user
                // Check '+clicked_branch_link' before deciding whether to use your Branch routing logic
            } else {
                LogUtils.d("BRANCH SDK Fail" + error.message)
            }
        }, intent.data, this)
    }
    
    override fun onNewIntent(intent: Intent) {
        super.onNewIntent(intent)
        this.intent = intent
    }

**Comment by derrick-branch** [comment]
@AmitPrajapati1902 it looks like this is an internet connectivity issue. 

Can you write into support@branch.io if this persists? Thank you.
