### ISSUE TITLE
Use androidx.browser:browser instead of customtabs

### ISSUE THREAD

**Issue by ubuntudroid** [BranchMetrics/android-branch-deep-linking-attribution#787]
The documentation advises to add `com.android.support:customtabs` to dependencies for 100% matching. However the customtabs library has been [superseded](https://developer.android.com/jetpack/androidx/migrate/artifact-mappings) by the `androidx.browser:browser` library.

It would be great if the branch SDK would be migrated to make use of the androidx one instead.

**Comment by apeterson-branch** [comment]
Ticket Filed:  `SDK-757`

**Comment by bklastaitis-branch** [comment]
As of version 4.+, Branch SDK already uses AndroidX. The Regarding this specific library import, the documentation does mention in a (recently added) comment that "androidx.browser:browser works just the same"
https://docs.branch.io/apps/android/#install-branch

We will make it clearer in the documentation that _any_ of the referenced library imports in the `com.android.support` namespace can be safely replaced with their androidx equivalents (DOCS-1101).

**Comment by danilobuerger** [comment]
@bklastaitis-branch it seems that strong matching is always disabled when using `androidx.browser` as the following check fails:

https://github.com/BranchMetrics/android-branch-deep-linking-attribution/blob/d1009831470166c2f393d65bfbefb2da0a16a05c/Branch-SDK/src/main/java/io/branch/referral/BranchStrongMatchHelper.java#L43-L52
