### ISSUE TITLE
Readme not updated for v4.3.1

### ISSUE THREAD

**Issue by Jeff11** [BranchMetrics/android-branch-deep-linking-attribution#797]
Is InstallListener not needed anymore with the updated dependency to install referrer? Please update readme. Maybe with an upgrade guide from 4.2 to 4.3.

**Comment by bklastaitis-branch** [comment]
Hi @Jeff11 , thanks for the report! The `InstallListener` entry has now been removed from README. We have sent out an email regarding migration to the newest SDK, the gist of it is that you should remove the `InstallListener` entry from the manifest.
