### ISSUE TITLE
Unexpected permission added in 4.3.x

### ISSUE THREAD

**Issue by K4KYA** [BranchMetrics/android-branch-deep-linking-attribution#799]
Updating from 4.2.1 -> 4.3.1

I noticed that branch is adding the [READ_PHONE_STATE](https://developer.android.com/reference/android/Manifest.permission#READ_PHONE_STATE) permission, which is a dangerous permission.

I can't see this documented anywhere, and can't see any reason why this has been added. Can we get some explanation of the permission requirement, or have it removed from the library? 

Updating to this would force our users to have to manually update, which we want to avoid.

Thanks

**Comment by Danyaga** [comment]
I had to remove it, because it was not acceptable for us with a proper explanation. My suggestion, for now, is to put in the androidManifest.xml

`<uses-permission
        android:name="android.permission.READ_PHONE_STATE"
        tools:node="remove" />`

**Comment by bklastaitis-branch** [comment]
Thanks for the report! SDK v4.3+ series bundles the Play Install Referrer library 1.1 together with the SDK, which inadvertently pulled in the READ_PHONE_STATE permission. We made a ticket to remove it (SDK-814).

**Comment by echo-branch** [comment]
Should be fixed in latest release.
