### ISSUE TITLE
Missing InstallListener class

### ISSUE THREAD

**Issue by Danyaga** [BranchMetrics/android-branch-deep-linking-attribution#804]
This crash is happening a lot in the last release i have done. Did you change the package of your InstallListener class by chance? Should I change it in my manifest file? Did i miss something?

 I'm using the version the following versions:
```
implementation 'io.branch.sdk.android:library:4.3.1'
implementation 'com.android.installreferrer:installreferrer:1.1.1'
```

Here my manifest file ([as it is still advertised in your readme file](https://github.com/BranchMetrics/android-branch-deep-linking-attribution/blob/6a6ec03c1e7e02d349bcfdaf0b233a7f5077835d/README.md#instant-app-deep-linking-and-attribution-support)):
```
<receiver
            android:name="io.branch.referral.InstallListener"
            android:exported="true"
            android:permission="android.permission.INSTALL_PACKAGES">

            <intent-filter>
                <action android:name="com.android.vending.INSTALL_REFERRER"/>
            </intent-filter>

        </receiver>
```

Here a crash report:
https://gist.github.com/Danyaga/ad98b4b61bde6fc4d64e6f53d960b8d5

EDIT
Ok, I got it. It is linked to this [chage](https://android-developers.googleblog.com/2019/11/still-using-installbroadcast-switch-to.html?mkt_tok=eyJpIjoiWkRsbVlURmpZamt6WXpCbSIsInQiOiJscmxoeHRBUlliMUZmQnZ0MHdUTmduUktDSjZDQUpNNlJmZ2s2TDJ6NmZZaklaMWFOcURSYmh3QWpvOU9GZXN4eFJrVHllNnFzTlZyUlZveTZXUHhRV2k3MGlMd0NmdDV2a1kxamFHQmlrRGtYK0RaUXFUeUNtU010YkpRdUZVVCJ9&_branch_match_id=619107135954245697). For who has the same problem, as reported in a email I got from Branch, we need to:
1. Remove those lines from the manifest file;
2. Update the implemented library version to 4.3.2 or above.

**Comment by echo-branch** [comment]
Reporter solved the issue

**Comment by Sottti** [comment]
Thanks @Danyaga for coming back and explain what was the problem!

**Comment by rinav** [comment]
Can we update the Readme as it still suggest to include these lines in manifest.

Also do advice if we need to remove the lib from the Gradle too `com.android.installreferrer:installreferrer:xxx`
