### ISSUE TITLE
Last deeplink always opened on warm start

### ISSUE THREAD

**Issue by markymark1988** [BranchMetrics/android-branch-deep-linking-attribution#805]
Version `4.3.2` of the Branch SDK.

Seems that the SDK unnecessarily opens deeplinks when resuming the app from the recents tray. 

Repro
- Back out of app
- Tap a branch deeplink to open the app to a specific screen
- Back out of app
- Resume app from recent apps tray (warm start)

This is where the SDK returns the same deeplink again and the user is taken to the deeplink screen. As a user, when resuming the app, I would expect to be taken to the home screen not the most recent deeplink that I tapped.
I would only expect to be taken to a deeplink screen if I, the user, initiated it by tapping a deeplink.

The following is from the logs when the app is resumed from the recent apps tray.
`I/BranchSDK: returned {"session_id":"753832097185850524","identity_id":"753822955268604331","link":"https://lfx2.app.link?%24identity_id=753822955268604331","data":"{\"+non_branch_link\":\"hsd-driver://static/invite?link_click_id=748366536037411539\",\"+clicked_branch_link\":false,\"+is_first_session\":false}","device_fingerprint_id":"700092944443127861"}`

---

There is a single launcher activity.
`branch.initSession()` is called in `onStart()`.
When the app is resumed from the recents tray `onInitFinished()` is called and the error response is null.

**Comment by bklastaitis-branch** [comment]
@markymark1988 that sounds like normal Android behavior, if you launch an app from the recent apps list, it will take you to the last visited place in your app. If you launch it from via the launcher icon, it will take you to home screen. As for the payload, it seems like that's a log from inside the SDK, the callback should only receive what is in the `data` field, so `{"+non_branch_link":"hsd-driver://static/invite?link_click_id=748366536037411539","+clicked_branch_link":false,"+is_first_session":false}` and I don't see any referring params there unless you are using the `non_branch_link` value to navigate somewhere. Let me know if that answers your question.

**Comment by markymark1988** [comment]
>if you launch an app from the recent apps list, it will take you to the last visited place in your app

It didn't take me to the last visible screen.
Scenario:
- Back out of app
- Tap deeplink and am taken to our `Invite Friends` screen
- Tap back button once and am taken to our `home` screen
- Tap back again and am taken out of the app

Here `home` was the last screen that I saw.
When I resume from the recents tray I'd expect to be taken to the `home` screen rather than the `Invite Friends` screen.

>If you launch it from via the launcher icon, it will take you to home screen.

I agree with this.

Yes, I'm using `+non_branch_link` as a fallback deeplink option.

**Comment by bklastaitis-branch** [comment]
I see, thanks for clarifying! Would you be able to post the payload and the response from the SDK during the first click and then during the (re)launch via the recent apps list?

**Comment by markymark1988** [comment]
## First click

### Referring params payload

`{"+non_branch_link":"hsd-driver:\/\/static\/invite?link_click_id=748366536037411539","+clicked_branch_link":false,"+is_first_session":false}`

### SDK response

`I/BranchSDK: posting to https://api2.branch.io/v1/open
I/BranchSDK: Post value = {"device_fingerprint_id":"700092944443127861","identity_id":"754366719795646446","hardware_id":"0550f070-cc1c-4057-bfdc-e10a7ea154b2","is_hardware_id_real":false,"brand":"Google","model":"Pixel 3","screen_dpi":440,"screen_height":2028,"screen_width":1080,"wifi":true,"ui_mode":"UI_MODE_TYPE_NORMAL","os":"Android","os_version":29,"cpu_type":"aarch64","build":"QQ1A.200205.002","locale":"en_US","connection_type":"wifi","device_carrier":"T-Mobile","os_version_android":"10","country":"US","language":"en","local_ip":"192.0.0.4","app_version":"4.9.3","facebook_app_link_checked":false,"is_referrable":0,"debug":true,"update":1,"latest_install_time":1581093265691,"latest_update_time":1581093507832,"first_install_time":1581093265691,"previous_update_time":1581093453366,"environment":"FULL_APP","external_intent_uri":"hsd-driver:\/\/static\/invite?link_click_id=748366536037411539","external_intent_extra":"{\"branch_intent\":true}","cd":{"mv":"-1","pn":"com.hopskipdrive.driver.beta"},"metadata":{},"link_identifier":"748366536037411539","lat_val":0,"google_advertising_id":"6a6d9321-84ab-4b1a-bd90-88e435c7e700","advertising_ids":{"aaid":"6a6d9321-84ab-4b1a-bd90-88e435c7e700"},"instrumentation":{"v1\/close-brtt":"53","v1\/open-qwt":"0"},"sdk":"android4.3.2","branch_key":"__hidden__"}
I/BranchSDK: returned {"session_id":"754368138547865552","identity_id":"754366719795646446","link":"https://lfx2.app.link?%24identity_id=754366719795646446","data":"{\"+non_branch_link\":\"hsd-driver://static/invite?link_click_id=748366536037411539\",\"+clicked_branch_link\":false,\"+is_first_session\":false}","device_fingerprint_id":"700092944443127861"}`

## Relaunch from recent apps tray

### Referring params payload (same as above)

`{"+non_branch_link":"hsd-driver:\/\/static\/invite?link_click_id=748366536037411539","+clicked_branch_link":false,"+is_first_session":false}`

### SDK response

`I/BranchSDK: posting to https://api2.branch.io/v1/open
I/BranchSDK: Post value = {"device_fingerprint_id":"700092944443127861","identity_id":"754366719795646446","hardware_id":"686de469-2595-49d0-8c65-82d54526ffc5","is_hardware_id_real":false,"brand":"Google","model":"Pixel 3","screen_dpi":440,"screen_height":2028,"screen_width":1080,"wifi":true,"ui_mode":"UI_MODE_TYPE_NORMAL","os":"Android","os_version":29,"cpu_type":"aarch64","build":"QQ1A.200205.002","locale":"en_US","connection_type":"wifi","device_carrier":"T-Mobile","os_version_android":"10","country":"US","language":"en","local_ip":"192.0.0.4","app_version":"4.9.3","facebook_app_link_checked":false,"is_referrable":0,"debug":true,"update":1,"latest_install_time":1581093265691,"latest_update_time":1581093507832,"first_install_time":1581093265691,"previous_update_time":1581093453366,"environment":"FULL_APP","external_intent_uri":"hsd-driver:\/\/static\/invite?link_click_id=748366536037411539","external_intent_extra":"{\"branch_intent\":true}","cd":{"mv":"-1","pn":"com.hopskipdrive.driver.beta"},"metadata":{},"lat_val":0,"google_advertising_id":"6a6d9321-84ab-4b1a-bd90-88e435c7e700","advertising_ids":{"aaid":"6a6d9321-84ab-4b1a-bd90-88e435c7e700"},"instrumentation":{"v1\/close-brtt":"88","v1\/open-qwt":"0"},"sdk":"android4.3.2","branch_key":"__hidden__"}
I/BranchSDK: returned {"session_id":"754368580200187370","identity_id":"754366719795646446","link":"https://lfx2.app.link?%24identity_id=754366719795646446","data":"{\"+non_branch_link\":\"hsd-driver://static/invite?link_click_id=748366536037411539\",\"+clicked_branch_link\":false,\"+is_first_session\":false}","device_fingerprint_id":"700092944443127861"}`

**Comment by bklastaitis-branch** [comment]
@markymark1988 would you provide the branch deeplink that you use the first time you launch the app? (before backing out and relaunching via the recent apps tray)

**Comment by markymark1988** [comment]
https://lfx2.test-app.link/c9gWkVGdtL

**Comment by iamatulkumar** [comment]
I am facing the same issue. in android version 4.3.2
returned {"session_id":"756045844436533926","identity_id":"**********","link":"https://pocketpills.app.link?%24identity_id=***********","data":"{\"+clicked_branch_link\":false,\"+is_first_session\":false}","device_fingerprint_id":"756027873215360906"}

**Comment by bklastaitis-branch** [comment]
Hi @markymark1988 , we looked at this last week and, in short, it seems to be the expected behavior. In particular, receiving the same intent is normal when user exits the app via the back button and then relaunches it via the recent apps list. The SDK reports that intent value to the server, which reports it back in the response json. Further, the SDK does recognize that the app was launched via a Branch link during the first session by parsing out the `link_identifier` value, which it (appropriately) does not do during the second session. Now, it seems like there may still be an issue because, during the first session, the server returns +clicked_branch_link=false and there are no referring parameters (if any are expected?). However most of the time this occurs when the Branch key tied to the link does not match the Branch key in your app (or due to another configuration related issue). You can safely share your Branch keys with our support team at support@branch.io who would be glad to help you resolve any configuration issues as well. However, within the scope if this ticket, the "+non_branch_link” value that you see in the returned json after a warm start that follows a Branch-link-initiated-session is the expected SDK/server behavior.

**Comment by markymark1988** [comment]
Got it, thanks, @bklastaitis-branch.

In particular, thanks for clarifying this point.
>receiving the same intent is normal when user exits the app via the back button and then relaunches it via the recent apps list

**Comment by derrick-branch** [comment]
@markymark1988 are you okay with me closing this, or is there still an issue here?

If there's still an issue, can you write into support@branch.io and reference this issue? Then hopefully they can work with you to debug.

**Comment by markymark1988** [comment]
Fine to close

**Comment by aadityapaliwal** [comment]
@mark-software @bklastaitis-branch I am also facing the same issue. Can you please suggest me how I can fix it?
