### ISSUE TITLE
[Question]usage of chrome custom tab internally

### ISSUE THREAD

**Issue by hotchemi** [BranchMetrics/android-branch-deep-linking-attribution#817]
## Overview

Hi, we're considering to use the SDK and let me clarify one point as for the usage of chrome custom tab.
I was reading [BranchStrongMatchHelper#checkForStrongMatch](https://github.com/BranchMetrics/android-branch-deep-linking-attribution/blob/536d40c3c6ff82704e4cdc8da5b67ea607488e6d/Branch-SDK/src/main/java/io/branch/referral/BranchStrongMatchHelper.java#L70-L137) and can I assume what this method does is attempts to load a certain URL to sync a cookie with Chrome Android app for matching(and if so is that possible?)?
I've never seen this kind of usage of the chrome custom tab actually and we definitely want to make sure what would be there under the hood to be accountable for our users 🙇 

Thank you in advance!

**Comment by bklastaitis-branch** [comment]
Hi @hotchemi just wanted to let you know that this wasn't ignored. We want to gather some more information in order to give a complete answer.

**Comment by bklastaitis-branch** [comment]
Hi again @hotchemi, your assumption is very close to reality. We do indeed attempt to match the cookie, however we don’t actually want to bring up the customtab UI, so we only call `mayLaunchUrl`, which makes the request without bringing up the associated UI elements. Note that this is not supported on iOS. This feature is one of the ways Branch ensures [deterministic matching](https://branch.io/glossary/deterministic-matching/).

The feature is disabled if chrome custom tabs are not imported. However, if you need that library for something else, you can still disable Branch's 100% matching by calling `Branch.enableCookieBasedMatching(null)` prior to session initialization (e.g. App.onCreate). It appears this isn't [documented](https://help.branch.io/developers-hub/docs/android-advanced-features#section-enable-100-matching) well, so we will edit the documentation (DOCS-1329) and will introduce an easier to understand method like `disableCookieBasedMatching` (SDK-931).

**Comment by hotchemi** [comment]
@bklastaitis-branch thank you so much for your kind response😄We noted!
