### ISSUE TITLE
Trouble initializing Branch.  Branch API Error: poor network connectivity.

### ISSUE THREAD

**Issue by harikesh59** [BranchMetrics/android-branch-deep-linking-attribution#844]
I/BranchSDK: posting to https://api2.branch.io/v1/install
I/BranchSDK: Post value = {"hardware_id":"bf63e4d7a06f52c2",
  "is_hardware_id_real":true,"brand":"OnePlus","model":"HD1901",
   "screen_dpi":420,"screen_height":2290,"screen_width":1080,
   "wifi":true,"ui_mode":"UI_MODE_TYPE_NORMAL","os":"Android",
   "os_version":29,"cpu_type":"aarch64","build":"HD1901_14_27",
   "locale":"en_IN","connection_type":"wifi","device_carrier":"airtel",
   "os_version_android":"10","country":"IN","language":"en",
   "local_ip":"10.1.45.26","app_version":"1.3.0",
   "facebook_app_link_checked":false,"is_referrable":0,
   "debug":false,"update":0,"latest_install_time":1589525769409,
   "latest_update_time":1589527302260,"first_install_time":1589525769409,
   "previous_update_time":0,"environment":"FULL_APP","cd":{"mv":"-1","pn":"in.app.debug"},
   "metadata":{},"advertising_ids":{"aaid":"130ac551-83ef-4374-a80b-"},"lat_val":0,
   "google_advertising_id":"130ac551-83ef-4374-a80b","instrumentation":{"v1\/install-qwt":"0","v1\/install-brtt":"104"},
   "sdk":"android5.0.1","branch_key":"key_test"}
I/BranchSDK: Http connect exception: Failed to connect to api2.branch.io/0.0.0.0:443
E/MainActivity$onStart: Trouble initializing Branch.  Branch API Error: poor network connectivity. Please try again later.

Working on Android Version : Pie 
Internet speed is around 100Mbps.

**Comment by hamidsn** [comment]
I am facing the same issue randomly.

**Comment by iamjaytong** [comment]
saw similar issues on Android 4 and turns out it's due to https://github.com/facebook/react-native/issues/23151. Hopefully this resolves the issue for some of you.

**Comment by StarryFire** [comment]
I am getting this same error on RN 0.62. @iamjaytong That issue is closed, how can that cause this issue?

**Comment by iamjaytong** [comment]
@StarryFire From the thread, someone posted a [gist](https://gist.github.com/patrickhammond/0b13ec35160af758d98c) with a workaround. It doesn't give many details on why it's needed, so here's Android's documentation about [security provider](https://developer.android.com/training/articles/security-gms-provider?authuser=1).

One thing I'd change to the workaround is using `implementation 'com.google.android.gms:play-services-safetynet:+'` in the `bundle.gradle` rather than a specified version.

**Comment by mgwedd** [comment]
> @StarryFire From the thread, someone posted a [gist](https://gist.github.com/patrickhammond/0b13ec35160af758d98c) with a workaround. It doesn't give many details on why it's needed, so here's Android's documentation about [security provider](https://developer.android.com/training/articles/security-gms-provider?authuser=1).
> 
> One thing I'd change to the workaround is using `implementation 'com.google.android.gms:play-services-safetynet:+'` in the `bundle.gradle` rather than a specified version.

This workaround solved the problem for me.

**Comment by tafelnl** [comment]
@hamidsn Did you find a solution to "Unable to resolve host "api2.branch.io". I have the same issue: #920

**Comment by jf-branch** [comment]
A lot of great insight for the Branch team to further investigate how we want our sdks to handle threading and queues in the future!

**Comment by DK070202** [comment]
We are using  [flutter_branch_sdk](https://pub.dev/packages/flutter_branch_sdk). 
```YAML
dependencies:
  flutter_branch_sdk: ^6.2.1
```
And we can find this is still happening in various versions of android devices. 
Any Idea why this is happening and what is the preferred solution for it?

<img width="1246" alt="Screenshot 2022-10-19 at 2 26 17 PM" src="https://user-images.githubusercontent.com/78605453/196645150-eb26f820-a0de-4974-b2a2-8a19ce5df852.png">

**Comment by procodingtools** [comment]
If you have AdBlock disable it.

**Comment by crazycoder-io** [comment]
> If you have an AdBlock disable it.

You saved my time, thank you! 🤩🙏

**Comment by Mihai-github** [comment]
+1

**Comment by gdeluna-branch** [comment]
As of https://github.com/BranchMetrics/android-branch-deep-linking-attribution/releases/tag/5.7.3 it should be more clear when this error occurs due to DNS policies.

**Comment by Mihai-github** [comment]
> > If you have an AdBlock disable it.
> 
> You saved my time, thank you! 🤩🙏

How do we see we have on our Android phone an AdBlocker and also there is no workaround for this? since it is such a limitation thinking it can be something that users really use and if so the branch on android devices will not work...

**Comment by shubham1295-droid** [comment]
I encountered the same issue: "Failed to connect to api2.branch.io/[::]:443 Check network connectivity or DNS settings."

I'm currently using version 5.16.3 (the latest as of now). This issue also appeared in previous versions; my earlier version was 5.4.0.

I noticed that the issue mentioned above was occurring because some of my testing devices did not have SIM cards. When I tested on a device with a SIM card, it worked perfectly.

**Comment by alainib** [comment]
i have a lot of error with "Failed to connect to api2.branch.io/[::]:443 Check network connectivity or DNS settings.", not sure why and how to solve them. if first init fail i cannot run another one 
i create a ticket here

https://github.com/BranchMetrics/android-branch-deep-linking-attribution/issues/1284
