### ISSUE TITLE
[Help needed] Android_id key is not send to analytics.

### ISSUE THREAD

**Issue by rasskazovaleksey** [BranchMetrics/android-branch-deep-linking-attribution#860]
Sdk version: 5.0.2

**Problem:** Sdk never sends [android_id](https://github.com/BranchMetrics/android-branch-deep-linking-attribution/blob/d51bbae458647b6643b873fde47be36411ed41a2/Branch-SDK/src/main/java/io/branch/referral/Defines.java#L56) to `/v1/install`. Instead [hardware_id](https://github.com/BranchMetrics/android-branch-deep-linking-attribution/blob/d51bbae458647b6643b873fde47be36411ed41a2/Branch-SDK/src/main/java/io/branch/referral/Defines.java#L55) is posted to API. Marketing team reports absence of data in `user_data.android_id` key in report. 

**Description:** In [setPost](https://github.com/BranchMetrics/android-branch-deep-linking-attribution/blob/d51bbae458647b6643b873fde47be36411ed41a2/Branch-SDK/src/main/java/io/branch/referral/ServerRequest.java#L185-L197) method [getBranchRemoteAPIVersion](https://github.com/BranchMetrics/android-branch-deep-linking-attribution/blob/d51bbae458647b6643b873fde47be36411ed41a2/Branch-SDK/src/main/java/io/branch/referral/ServerRequest.java#L647-L649) is always BRANCH_API_VERSION.V1. This forces to always append [updateRequestWithV1Params](https://github.com/BranchMetrics/android-branch-deep-linking-attribution/blob/d51bbae458647b6643b873fde47be36411ed41a2/Branch-SDK/src/main/java/io/branch/referral/DeviceInfo.java#L65).  Which appends [hardware_id](https://github.com/BranchMetrics/android-branch-deep-linking-attribution/blob/d51bbae458647b6643b873fde47be36411ed41a2/Branch-SDK/src/main/java/io/branch/referral/Defines.java#L55) to post method versus [updateRequestWithV2Params](https://github.com/BranchMetrics/android-branch-deep-linking-attribution/blob/d51bbae458647b6643b873fde47be36411ed41a2/Branch-SDK/src/main/java/io/branch/referral/DeviceInfo.java#L150) witch actually adds [android_id](https://github.com/BranchMetrics/android-branch-deep-linking-attribution/blob/d51bbae458647b6643b873fde47be36411ed41a2/Branch-SDK/src/main/java/io/branch/referral/Defines.java#L56)

**Questions:** 

1. Is it correct behaviour (lack of user_data.android_id field in report)?
2. How can we add data from SystemObserver.UniqueId to branch io report?

PS. Thank you for responce.

**Comment by kalbaxa** [comment]
This happens when `user_data_aaid` is available per docs https://help.branch.io/using-branch/docs/advertising-identifiers-for-attribution. Would be good if branch.io team can confirm.

**Comment by rasskazovaleksey** [comment]
Closing since confermed with support: android_id is not utilised if aaid is sent by device
Documentation: https://help.branch.io/using-branch/docs/advertising-identifiers-for-attribution#section-android-identifiers
