### ISSUE TITLE
addInstallMetadata fields do not appear in custom data.

### ISSUE THREAD

**Issue by jd565** [BranchMetrics/android-branch-deep-linking-attribution#870]
When adding install metadata using the Branch.addInstallMetadata method, the metadata added does not appear in the custom data of the install event.

Looking at the `updateRequestMetadata` method of `ServerRequest`, the install metadata gets added with each individual metadata item added to the base params object, but the generic request metadata is added as an object to the `Defines.Jsonkey.Metadata` key.

When I use `Branch.setRequestMetadata` rather than `Branch.addInstallMetadata` then the metadata appears in the custom data of the install event as expected.

This is using branch android sdk v5.0.3

**Comment by jf-branch** [comment]
Hi @jd565, 

If you wish to apply metadata to all Branch requests please utilize `.setRequestMetadata`

If you wish to apply metadata to a specific event please follow our current event logging guide: https://help.branch.io/developers-hub/docs/tracking-commerce-content-lifecycle-and-custom-events

**Comment by amank22** [comment]
Can you explain how install metadata is used if we can not access it in branch panel anywhere and not even in exported data.
