### ISSUE TITLE
Branch shows "Request to Branch server timed out" after 5.0.4 version.

### ISSUE THREAD

**Issue by AlonParker** [BranchMetrics/android-branch-deep-linking-attribution#902]
Hello!
Immediately after the application's cold start gives a timeout error, although 5.5 seconds have not passed for the request.

**Trouble initializing Branch.  Request to Branch server timed out. Please check your internet connectivity**

In version 5.0.4, everything works fine. The problem appears after this version, I tried 5.0.5, 5.0.6 and 5.0.7

**Comment by jf-branch** [comment]
Hey @AlonParker 

Wanted to follow up to see if you could provide additional logs/stack traces.

**Comment by AlonParker** [comment]
Hey @jf-branch
It was a long time ago, I can no longer provide additional information, maybe this is no longer relevant

**Comment by jf-branch** [comment]
Thanks for the insight @mochadwi, going to close this out and a new one can be opened if anyone is still experiencing a similar issue.
