### ISSUE TITLE
[AndroidManifest] String Resource not recognised by IntegrationValidator

### ISSUE THREAD

**Issue by cuberob** [BranchMetrics/android-branch-deep-linking-attribution#915]
When using a string resource to define the custom scheme in the AndroidManifest.xml file (e.g. `@string/custom_scheme`). The IntegrationValidator doesn't recognise the setup correctly, as it doesn't resolve the actual associated resource, it only tries to compare the expected path with the id.

This caused quite some confusion on my end, as the custom scheme was validated to be working, yet branch refused to pass this integration test. Supporting string resources is especially useful when managing multiple app flavors.

**Comment by agerstner-branch** [comment]
Look for this fix in 5.0.13
