### ISSUE TITLE
bug: [android] Http connect exception for "api2.branch.io"

### ISSUE THREAD

**Issue by tafelnl** [BranchMetrics/android-branch-deep-linking-attribution#920]
On initializing the branch SDK I get the following error:
```
I/BranchSDK: posting to https://api2.branch.io/v1/install
I/BranchSDK: Http connect exception: Unable to resolve host "api2.branch.io": No address associated with hostname
```
I could reproduce this error on a Samsung S10 with Android 9. It used to work before on the exact same device. No changes are made to the code as far as I am aware. I tried SDK `implementation 'io.branch.sdk.android:library:5.0.3'` through `implementation 'io.branch.sdk.android:library:5.0.8'`

On the other hand, on a Samsung 9 with Android 10 it does not produce any error at all.

**Comment by tafelnl** [comment]
It might be related to #844 . But the solutions mentioned there ([this one for example](https://gist.github.com/patrickhammond/0b13ec35160af758d98c)) do not solve it unfortunately.

**Comment by tafelnl** [comment]
Okay, so I found out why it refused to work. The phone I was testing on, was using an ad-blocker. The ad-blocker blocks all requests to `api2.branch.io` all together. Disabling the ad-blocker solved the problem. I am not sure if it is fair for this major ad-blocker to block those API endpoints. I guess it is, since it allows for cross-application attribution.

**Comment by vishalkumarsinghvi** [comment]
@tafelnl  Thank you so much I used adblocking DNS that's why My branch is not working after turn off working fine.

**Comment by vishalkumarsinghvi** [comment]
But most of people will use adblocker they can't use branch io SDK :(

**Comment by tafelnl** [comment]
You are correct, I also changed my mind about this. Branch should use a fallback when people are using an addblocker. Branch should in such a case just rely on the native deeplinking ability.

**Comment by jf-branch** [comment]
Thanks for the input all, the Branch team is certainly taking this into consideration as we continue to develop our product.

**Comment by ahnafnafee** [comment]
Any updates on a fallback for users using adblock?

**Comment by jf-branch** [comment]
Hi all, we have implemented a default retry limit for non fail-able requests such as no internet or ad blocked with release 5.2.2. The default is 3, but you can override that and set your own through https://github.com/BranchMetrics/android-branch-deep-linking-attribution/blob/master/Branch-SDK/src/main/java/io/branch/referral/Branch.java#L746

**Comment by tafelnl** [comment]
@jf-branch Thanks for the update. But I don't think it actually solves the issue in _this_ thread right? Because as long as the adblocker is enabled, it will block all HTTP requests to the `branch.io` host (depending on the adblocker of course, but the ones I tested, block this host by default). So you can retry all you want, but it will keep blocking them.

**Comment by jf-branch** [comment]
@tafelnl correct, this does not allow for branch to bypass the Adblocker to make the request. Unfortunately there is not much we can do to stop the ad blocker from blacklisting us.

**Comment by tafelnl** [comment]
Agreed. But it may be well possible to implement some sort of fallback. Of course we cannot do the attribution we could have done otherwise. But we can resort to the native default deeplinking ability provided by Android/iOS and do some basic stuff.

**Comment by tafelnl** [comment]
Of course shortened links are quite useless then (since the SDK would not be able to transform them into the correct data). But the long links would still work quite well.

**Comment by Mihai-github** [comment]
for me this is still not working

**Comment by Mihai-github** [comment]
> Okay, so I found out why it refused to work. The phone I was testing on, was using an ad-blocker. The ad-blocker blocks all requests to `api2.branch.io` all together. Disabling the ad-blocker solved the problem. I am not sure if it is fair for this major ad-blocker to block those API endpoints. I guess it is, since it allows for cross-application attribution.

How do I see if I have the adblocker on since I don't have any application installed for this?

**Comment by brianinator** [comment]
@tafelnl "The phone I was testing on, was using an ad-blocker." What ad-blocker specifically was installed?

**Comment by brianinator** [comment]
I have been able to reproduce issue with the following steps:

1. Open Android device.
2. Open Google Play Store.
3. Download & install Wize Adblock app.
4. Open and activate/enable Wize Adblock blocking on Home tab.
5. Open your app with Branch. (This is to get Wize to track activity with domain: `api2.branch.io`)
6. Close your app completely.
7. Go back to Wize Adblock app and open Activity tab.
8. Find `api2.branch.io` in Activity tab. 
9. Tap on it.
10. Hit the bottom button: “Add to Forwarded”.
11. Reopen your app.

Yeah so depends on your app's error handling if you can see it. My company's app reports errors to App Center so I can see it there.
