### ISSUE TITLE
Deeplink parameters are not passed to the application when the user installs the app for first time by clicking on the link

### ISSUE THREAD

**Issue by lounerios** [BranchMetrics/android-branch-deep-linking-attribution#925]
Last two weeks we have noticed a strange behavior.
If the user tries to install the application through the deeplink, the parameters are not passed when the application is opened for first time after the installation.

However if the application is installed and the user clicks on the link, the parameters are passed correctly.

**Comment by raheelmushtaq** [comment]
@lounerios 
How were you able to resolve this issue.

I am currently facing this issue on my side.

I am trying to install the application through deeplink. App is opened in playstore. Then I install the app. and I press open button, my app starts from splash and no parameters get passed.

**Comment by lounerios** [comment]
@raheelmushtaq 
We have managed to resolve the issue.
We have found that the problem depends on the browser that we use to open the deeplink.

Also,  in my app, i used a different activity than the main to check the deeplink parameters.

**Comment by raheelmushtaq** [comment]
@lounerios 
Thank you for the reply.
I was also able to resolve this by adding the branch handling the launcher Activity, when the app got installed for the first time After Install. Branch fetches the data for me.
With this I was able to resolve this issue on my side.


And Again Thanks for the reply.
