### ISSUE TITLE
Force delete intent when exit the app from device back button

### ISSUE THREAD

**Issue by Solid-Metal** [BranchMetrics/android-branch-deep-linking-attribution#930]
its the same issue from here, but since its already closed, i have no way to make new thread from it : https://github.com/BranchMetrics/android-branch-deep-linking-attribution/issues/805

while as i understand it, its "expected behaviour" from android, in our app it create problem

and as i look at it, theres no indication on parameter that the SDK interpreted for me to make additional validation, so my question is

is there any way for us to force delete the intent after we already processed it ?, i'm using React-Native implementation for this

**Comment by agerstner-branch** [comment]
You can check if the application was launched by the "Recent Apps" list by checking for the flag FLAG_ACTIVITY_LAUNCHED_FROM_HISTORY. I hope this helps.
https://developer.android.com/reference/android/content/Intent#FLAG_ACTIVITY_LAUNCHED_FROM_HISTORY
