### ISSUE TITLE
ERROR: Trouble initializing Branch.  Request to Branch server timed out. Please check your internet connectivity

### ISSUE THREAD

**Issue by raquelmsmith** [BranchMetrics/android-branch-deep-linking-attribution#946]
I have integrated branch in my app and it works maybe 60% of the time. It is not an issue with keys, because it _does_ work. 

Frequently when the app is opened (not from background, but from closed) I get this error:

```
Trouble initializing Branch.  Request to Branch server timed out. Please check your internet connectivity
```

I have used `netInfo.isConnected.toString()` just before the `branch.subscribe()` call and I am connected to the internet. Fast internet! 

I have tried the other solutions for the security provider. How do I get Branch to connect consistently? Any suggestions for debugging this? How do I get more info out of the error?

**Comment by raquelmsmith** [comment]
@jf-branch @agerstner-branch any help on this? Seems to only be android.

**Comment by raquelmsmith** [comment]
Ping? Please? I really don't want to have to find another library.

**Comment by agerstner-branch** [comment]
Hi @raquelmsmith, unfortunately, there's not enough here for us to reproduce, however here are some questions/things to try:

When you say you have a ~60% success rate, is this on a single device, or 60% of devices succeed while the rest consistently fail? Is it possible that there is an adblocker on the device blocking/hindering the calls?

What is the current timeout set at? Default is 5.5 seconds, does increasing this change the success rate at all? If so, then connectivity is worth looking into, if not, then the issue could be something else disguised as a connectivity issue.

Couple things to try:
Put breakpoints on:
ServerRequestRegisterInstall::112
ServerRequestRegisterOpen::95
And then send us the call stack when it hits either of these.

Also, put breakpoints on:
Branch::2168
Branch::2170
Capture the server request, convert to a cURL and see what the response is, how long it takes, does it work from the device, etc. Additionally, you can try setting up a proxy and see what goes through it.

**Comment by raquelmsmith** [comment]
> When you say you have a ~60% success rate, is this on a single device, or 60% of devices succeed while the rest consistently fail? Is it possible that there is an adblocker on the device blocking/hindering the calls?

60% on a single device. Sometimes it succeeds, most often it doesn't. I haven't installed any ad blocker. How would I do that or see if one is installed?

> What is the current timeout set at? Default is 5.5 seconds, does increasing this change the success rate at all? If so, then connectivity is worth looking into, if not, then the issue could be something else disguised as a connectivity issue.

How do I set the timeout?

I can do the breakpoints you suggested over the next couple of days.

**Comment by agerstner-branch** [comment]
> 60% on a single device. Sometimes it succeeds, most often it doesn't. I haven't installed any ad blocker. How would I do that or see if one is installed?
You most likely do not have one, then. To rule out anything specific to your device, try creating an emulator and run your app there. If you see the same behavior, it is likely a code issue. If not, you'll want to focus troubleshooting on your device.

> How do I set the timeout?
https://github.com/BranchMetrics/android-branch-deep-linking-attribution/blob/master/Branch-SDK/src/main/java/io/branch/referral/Branch.java#L705-L709

Hope this helps!

**Comment by raquelmsmith** [comment]
Adding the timeout seems to have helped!

**Comment by agerstner-branch** [comment]
That's good news! I suggest checking the internet speed on your test device as the default timeout should normally be sufficient and not require changing. Closing issue. Please open a new issue if you have new findings you need us to address.
