### ISSUE TITLE
Branch.getAutoInstance(this) Throughing Error For ReadKey

### ISSUE THREAD

**Issue by Nadeembhat-Cohesion** [BranchMetrics/android-branch-deep-linking-attribution#952]
I am getting the below issue, while I am using the 5.0.15 version of SDK. 
on this method inside Application Class -> Branch.getAutoInstance(this)
`

        Caused by: android.content.res.Resources$NotFoundException: String resource ID #0x0
        at android.content.res.Resources.getText(Resources.java:444)
        at android.content.res.Resources.getString(Resources.java:537)
        at io.branch.referral.BranchUtil.readBranchKey(BranchUtil.java:109)
        at io.branch.referral.Branch.getAutoInstance(Branch.java:453)
`

**Comment by Nadeembhat-Cohesion** [comment]
I tried another method and it worked 
Branch.getAutoInstance(this@context, "Key")

**Comment by agerstner-branch** [comment]
Hello @Nadeembhat-Cohesion you need to specify your branchKey either in the AndroidManifest.xml file or in /assets/branch.json file. Can you verify one of these are present?

**Comment by Nadeembhat-Cohesion** [comment]
@agerstner-branch Yes i am using in AndroidManifest.xml file
`
 <meta-data
                android:name="io.branch.sdk.BranchKey"
                android:value="${branchKey}" />
            <meta-data
                android:name="io.branch.sdk.BranchKey.test"
                android:value="${branchKey}" />
            <meta-data
                android:name="io.branch.sdk.TestMode"
                android:value="true" /> 
`

**Comment by Nadeembhat-Cohesion** [comment]
@agerstner-branch  Thanks for Quick Reply it was my bad .Its working now
