### ISSUE TITLE
Respect user's opt-out of advertising IDs

### ISSUE THREAD

**Issue by chao2zhang** [BranchMetrics/android-branch-deep-linking-attribution#959]
https://developer.android.com/training/articles/user-data-ids

_Always respect the associated Personalized Ads flag. Advertising IDs are configurable in that users can limit the amount of tracking associated with the ID. Always use the AdvertisingIdClient.Info.isLimitAdTrackingEnabled() method to ensure that you aren't circumventing your users' wishes._

This method is not currently invoked in `GAdsPrefetchTask`. This means that apps using branch is likely violating Google's policy starting "Early 2022". https://support.google.com/googleplay/android-developer/answer/6048248?hl=en.

**Comment by jf-branch** [comment]
Hi @chao2zhang, Thank you for posting your concern. 

Branch works very closely with Google to ensure we are adhering and adapting to their policies. We have already updated our dev docs to recognize the need for clients to include the AD_ID use permission within their manifest or use version 17.1.0+ of the play-services-ads-identifier library, in which the permission is declared in that manifest and therefore will be merged. We will also be posting a blog post and sending out an email about this requirement next week. 

Additionally, as I am sure you are aware, currently, apps targeting API 31 on Android 12 devices who do have Limit Ad Tracking enabled, their AD ID is zeroed out entirely.

**Comment by chao2zhang** [comment]
Thanks for taking care of the permission issue - I think my question is related to the usage of `AdvertisingIdClient.Info.isLimitAdTrackingEnabled()`.
_Always use the AdvertisingIdClient.Info.isLimitAdTrackingEnabled() method to ensure that you aren't circumventing your users' wishes_

**Comment by chao2zhang** [comment]
Looks like we are actually respecting users choice by calling https://github.com/BranchMetrics/android-branch-deep-linking-attribution/blob/f1ffd1ad482fa1a8a80fa4c252135e964885040b/Branch-SDK/src/main/java/io/branch/referral/GAdsPrefetchTask.java#L46.
