### ISSUE TITLE
Data Safety Collection in Play Store

### ISSUE THREAD

**Issue by mochadwi** [BranchMetrics/android-branch-deep-linking-attribution#994]
https://support.google.com/googleplay/android-developer/answer/10787469?hl=en#zippy=%2Cdata-handling%2Cunderstand-the-csv-format%2Cimport-from-a-csv-file%2Coptional-format-for-sdks:~:text=any%20user%20data).-,Optional%20format%20for%20SDKs,-If%20you%27re%20an

As recent update from Google does this requires Branch to submit an SDK response regarding the data safety as well? or does it only for app developer?

**Comment by jf-branch** [comment]
Hi @mochadwi This might help you https://help.branch.io/using-branch/docs/answering-the-google-play-store-privacy-questions. We also have updated the SDK Console to reference our policy pages.
