### ISSUE TITLE
App already Installed and clicking on deeplink from Email, it is not opening app

### ISSUE THREAD

**Issue by rituapplocum** [BranchMetrics/android-branch-deep-linking-attribution#997]
Gradle Setup
implementation('io.branch.sdk.android:library:5.2.0')

Manifest Setup

`<activity
            android:name=".ui.splash.SplashActivity"
            android:exported="true"
            android:launchMode="singleTask"
            android:screenOrientation="portrait"
            android:theme="@style/SplashTheme"
            tools:ignore="LockedOrientationActivity">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>

            
            <intent-filter>
                <data
                    android:host="open"
                    android:scheme="appname" />
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
            </intent-filter>

            
            <intent-filter android:autoVerify="true">
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />

                <data
                    android:host="appname.com"
                    android:scheme="https" />
                <data
                    android:host="appname-staging.app.link"
                    android:scheme="https" />
                <data
                    android:host="appname-staging-alternate.app.link"
                    android:scheme="https" />
                <data
                    android:host="appname-staging.test-app.link"
                    android:scheme="https" />

            </intent-filter>
        </activity>`

**Comment by mochadwi** [comment]
seems this issues also occurred to us as no branch.io changes happened in our ends

**Comment by jf-branch** [comment]
Hi @rituapplocum and @mochadwi given Email integrations require a bit more context, could you please file tickets with our support team through https://help.branch.io/using-branch/page/submit-a-ticket as they can work with you to find the solution you are looking for.
